<?php
/**
 * @file
 * Add required JS to AJAX views.
 */

/**
 * Implements hook_library_info().
 */
function views_ajax_history_library_info() {
  $libraries = array();

  $lib_path = backdrop_get_path('module', 'views_ajax_history') . '/js/history.js';

  // Make sure we have a valid library path before returning library load info.
  if (!empty($lib_path)) {
    $libraries['history.js'] = array(
      'title' => 'history.js',
      'website' => 'https://github.com/browserstate/history.js',
      'version' => '1.8b2',
      'js' => array(
        $lib_path . '/scripts/bundled/html4+html5/jquery.history.js' => array(),
      ),
    );
  }
  return $libraries;
}

/**
 * Implements hook_views_pre_render().
 */
function views_ajax_history_views_pre_render($view) {
  if ($view->use_ajax && !$view->editing) {
    // @TODO add option to views form for html4+html5 or html5 only

    backdrop_add_library('views_ajax_history', 'history.js');
    backdrop_add_js(backdrop_get_path('module', 'views_ajax_history') . '/js/views_ajax_history.js', array('weight' => 10));
    backdrop_add_js(array('viewsAjaxHistory' => array('renderPageItem' => isset($_GET['page']) ? $_GET['page'] : 0)), 'setting');
  }
}
